name: Build
on:
  workflow_call:
jobs:
  build:
    name: Build Windows x64
    runs-on: windows-2022
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x
      - name: Publish
        run: dotnet publish src/SourceGit.csproj -c Release -o publish -r win-x64
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: sourcegit.win-x64
          path: publish/*
